steps:
  - name: "gcr.io/cloud-builders/npm"
    args: ["install"]

  - name: "gcr.io/cloud-builders/gcloud"
    args: ["app", "deploy", "app.yaml", "--quiet"]  # Adding --quiet to suppress interactive prompts

  - name: 'hashicorp/terraform:light'
    args: ['init']
    dir: './dev'  # Specify the directory for the dev environment

  - name: 'hashicorp/terraform:light'
    args: ['apply', '-auto-approve']
    dir: './dev'  # Specify the directory for the dev environment

  - name: 'hashicorp/terraform:light'
    args: ['init']
    dir: './prod'  # Specify the directory for the prod environment

  - name: 'hashicorp/terraform:light'
    args: ['apply', '-auto-approve']
    dir: './prod'  # Specify the directory for the prod environment

options:
  logging: CLOUD_LOGGING_ONLY  # Log options: CLOUD_LOGGING_ONLY or NONE if no logs are required
  default_logs_bucket_behavior: REGIONAL_USER_OWNED_BUCKET  # Use user-owned logs bucket behavior
