steps:
  # Install dependencies
  - name: "gcr.io/cloud-builders/npm"
    args: ["install"]

  # # # Build the application
  # - name: 'gcr.io/cloud-builders/npm'
  #   args: ['start']

  #  - name: 'gcr.io/cloud-builders/npm'
  #     args: ['install', '-g', 'pm2']

  - name: "gcr.io/cloud-builders/gcloud"
    args: ["app", "deploy", "app.yaml"]

  - name: "gcr.io/cloud-builders/gcloud"
    entrypoint: "bash"
    args:
      - "-c"
      - |
        # List and delete old App Engine versions
        versions=$(gcloud app versions list \
          --service default \
          --sort-by '~VERSION.ID' \
          --format 'value(VERSION.ID)' | sed 1,5d)
        for version in $versions; do
          gcloud app versions delete "$version" \
            --service default \
            --quiet
        done
