steps:
  - name: "gcr.io/cloud-builders/npm"
    args: ["install"]

  - name: "gcr.io/cloud-builders/gcloud"
    args: ["app", "deploy", "app.yaml", "--quiet"]  # Adding --quiet to suppress interactive prompts

options:
  logging: CLOUD_LOGGING_ONLY  # Change to CLOUD_LOGGING_ONLY or NONE if no logs are required
  default_logs_bucket_behavior: REGIONAL_USER_OWNED_BUCKET  # Use this option for user-owned logs bucket

